export const GA4_DIMENSIONS = `| API 名                           | 説明 |
| -------------------------------- | ------------------------------------------------------------ |
| achievementId                    | ゲーム内実績ID（achievement_idパラメータから取得） |
| adFormat                         | 広告表示形式（例: Interstitial, Banner, Rewarded, Native advanced） |
| adSourceName                     | 広告配信元ネットワーク名（例: AdMob Network, Facebook Audience） |
| adUnitName                       | 広告ユニット名（アプリ内広告枠の名称） |
| appVersion                       | アプリバージョン（Android: versionName, iOS: short bundle version） |
| audienceId                       | オーディエンスの数値ID（イベント期間中の所属グループ） |
| audienceName                     | オーディエンス名（所属グループの名称） |
| audienceResourceName             | オーディエンスのリソース名（一意識別用） |
| brandingInterest                 | ユーザーの興味・関心 |
| browser                          | 使用ブラウザ名 |
| campaignId                       | キャンペーンID（マーケティングキャンペーン識別） |
| campaignName                     | キャンペーン名（マーケティングキャンペーン名称） |
| character                        | ゲーム内キャラクター名（イベント時のキャラクター） |
| city                             | ユーザーアクション発生都市 |
| cityId                           | 都市の地域ID（IPから取得） |
| cm360AccountId                   | CM360アカウントID（キャンペーンマネージャー識別） |
| cm360AccountName                 | CM360アカウント名 |
| cm360AdvertiserId                | CM360広告主ID |
| cm360AdvertiserName              | CM360広告主名 |
| cm360CampaignId                  | CM360キャンペーンID |
| cm360CampaignName                | CM360キャンペーン名 |
| cm360CreativeFormat              | CM360クリエイティブ形式（タイプ） |
| cm360CreativeId                  | CM360クリエイティブID |
| cm360CreativeName                | CM360クリエイティブ名 |
| cm360CreativeType                | CM360クリエイティブタイプ（カテゴリ） |
| cm360CreativeTypeId              | CM360クリエイティブタイプID |
| cm360CreativeVersion             | CM360クリエイティブバージョン |
| cm360Medium                      | CM360メディア（プレースメント課金形態） |
| cm360PlacementCostStructure      | CM360プレースメント課金形態（例: CPM） |
| cm360PlacementId                 | CM360プレースメントID（広告表示場所） |
| cm360PlacementName               | CM360プレースメント名 |
| cm360RenderingId                 | CM360レンダリングID |
| cm360SiteId                      | CM360サイトID |
| cm360SiteName                    | CM360サイト名 |
| cm360Source                      | CM360参照元（サイト名） |
| cm360SourceMedium                | CM360参照元/メディア |
| cohort                           | コホート名（ユーザーグループ） |
| cohortNthDay                     | 日次コホート（初回セッションからの日数） |
| cohortNthMonth                   | 月次コホート（初回セッションからの月数） |
| cohortNthWeek                    | 週次コホート（初回セッションからの週数） |
| contentGroup                     | コンテンツグループ（公開コンテンツのカテゴリ） |
| contentId                        | コンテンツID（content_idパラメータ） |
| contentType                      | コンテンツタイプ（content_typeパラメータ） |
| continent                        | ユーザーアクション発生大陸 |
| continentId                      | 大陸ID（IPから取得） |
| country                          | ユーザーアクション発生国 |
| countryId                        | 国ID（ISOコード、IP取得） |
| currencyCode                     | 通貨コード（eコマース用、ISO4217） |
| date                             | イベント日付（YYYYMMDD） |
| dateHour                         | 日時（YYYYMMDDHH） |
| dateHourMinute                   | 日時（YYYYMMDDHHMM） |
| day                              | 日付（01～31） |
| dayOfWeek                        | 曜日（数値、0=日曜） |
| dayOfWeekName                    | 曜日名（英語） |
| defaultChannelGroup              | デフォルトチャネルグループ（参照元・メディア基準） |
| deviceCategory                   | デバイスカテゴリ（PC/タブレット/モバイル） |
| deviceModel                      | モバイルデバイスモデル |
| dv360AdvertiserId                | DV360広告主ID |
| dv360AdvertiserName              | DV360広告主名 |
| dv360CampaignId                  | DV360キャンペーンID |
| dv360CampaignName                | DV360キャンペーン名 |
| dv360CreativeFormat              | DV360クリエイティブ形式 |
| dv360CreativeId                  | DV360クリエイティブID |
| dv360CreativeName                | DV360クリエイティブ名 |
| dv360ExchangeId                  | DV360エクスチェンジID |
| dv360ExchangeName                | DV360エクスチェンジ名 |
| dv360InsertionOrderId            | DV360広告掲載オーダーID |
| dv360InsertionOrderName          | DV360広告掲載オーダー名 |
| dv360LineItemId                  | DV360広告申込情報ID |
| dv360LineItemName                | DV360広告申込情報名 |
| dv360Medium                      | DV360メディア（例: cpm） |
| dv360PartnerId                   | DV360パートナーID |
| dv360PartnerName                 | DV360パートナー名 |
| dv360Source                      | DV360参照元（サイト名） |
| dv360SourceMedium                | DV360参照元/メディア |
| eventName                        | イベント名 |
| fileExtension                    | ダウンロードファイルの拡張子（例: pdf, txt） |
| fileName                         | ダウンロードファイルのパス |
| firstSessionDate                 | 初回セッション日（YYYYMMDD） |
| firstUserCampaignId              | 初回獲得キャンペーンID |
| firstUserCampaignName            | 初回獲得キャンペーン名 |
| firstUserCm360AccountId          | 初回獲得CM360アカウントID |
| firstUserCm360AccountName        | 初回獲得CM360アカウント名 |
| firstUserCm360AdvertiserId       | 初回獲得CM360広告主ID |
| firstUserCm360AdvertiserName     | 初回獲得CM360広告主名 |
| firstUserCm360CampaignId         | 初回獲得CM360キャンペーンID |
| firstUserCm360CampaignName       | 初回獲得CM360キャンペーン名 |
| firstUserCm360CreativeFormat     | 初回獲得CM360クリエイティブ形式 |
| firstUserCm360CreativeId         | 初回獲得CM360クリエイティブID |
| firstUserCm360CreativeName       | 初回獲得CM360クリエイティブ名 |
| firstUserCm360CreativeType       | 初回獲得CM360クリエイティブタイプ |
| firstUserCm360CreativeTypeId     | 初回獲得CM360クリエイティブタイプID |
| firstUserCm360CreativeVersion    | 初回獲得CM360クリエイティブバージョン |
| firstUserCm360Medium             | 初回獲得CM360メディア |
| firstUserCm360PlacementCostStructure | 初回獲得CM360プレースメント課金形態 |
| firstUserCm360PlacementId        | 初回獲得CM360プレースメントID |
| firstUserCm360PlacementName      | 初回獲得CM360プレースメント名 |
| firstUserCm360RenderingId        | 初回獲得CM360レンダリングID |
| firstUserCm360SiteId             | 初回獲得CM360サイトID |
| firstUserCm360SiteName           | 初回獲得CM360サイト名 |
| firstUserCm360Source             | 初回獲得CM360参照元 |
| firstUserCm360SourceMedium       | 初回獲得CM360参照元/メディア |
| firstUserDefaultChannelGroup     | 初回獲得デフォルトチャネルグループ |
| firstUserDv360AdvertiserId       | 初回獲得DV360広告主ID |
| firstUserDv360AdvertiserName     | 初回獲得DV360広告主名 |
| firstUserDv360CampaignId         | 初回獲得DV360キャンペーンID |
| firstUserDv360CampaignName       | 初回獲得DV360キャンペーン名 |
| firstUserDv360CreativeFormat     | 初回獲得DV360クリエイティブ形式 |
| firstUserDv360CreativeId         | 初回獲得DV360クリエイティブID |
| firstUserDv360CreativeName       | 初回獲得DV360クリエイティブ名 |
| firstUserDv360ExchangeId         | 初回獲得DV360エクスチェンジID |
| firstUserDv360ExchangeName       | 初回獲得DV360エクスチェンジ名 |
| firstUserDv360InsertionOrderId   | 初回獲得DV360広告掲載オーダーID |
| firstUserDv360InsertionOrderName | 初回獲得DV360広告掲載オーダー名 |
| firstUserDv360LineItemId         | 初回獲得DV360広告申込情報ID |
| firstUserDv360LineItemName       | 初回獲得DV360広告申込情報名 |
| firstUserDv360Medium             | 初回獲得DV360メディア |
| firstUserDv360PartnerId          | 初回獲得DV360パートナーID |
| firstUserDv360PartnerName        | 初回獲得DV360パートナー名 |
| firstUserDv360Source             | 初回獲得DV360参照元 |
| firstUserDv360SourceMedium       | 初回獲得DV360参照元/メディア |
| firstUserGoogleAdsAccountName    | 初回獲得Google広告アカウント名 |
| firstUserGoogleAdsAdGroupId      | 初回獲得Google広告広告グループID |
| firstUserGoogleAdsAdGroupName    | 初回獲得Google広告広告グループ名 |
| firstUserGoogleAdsAdNetworkType  | 初回獲得Google広告ネットワークタイプ |
| firstUserGoogleAdsCampaignId     | 初回獲得Google広告キャンペーンID |
| firstUserGoogleAdsCampaignName   | 初回獲得Google広告キャンペーン名 |
| firstUserGoogleAdsCampaignType   | 初回獲得Google広告キャンペーンタイプ |
| firstUserGoogleAdsCreativeId     | 初回獲得Google広告クリエイティブID |
| firstUserGoogleAdsCustomerId     | 初回獲得Google広告顧客ID |
| firstUserGoogleAdsKeyword        | 初回獲得Google広告キーワード |
| firstUserGoogleAdsQuery          | 初回獲得Google広告検索クエリ |
| firstUserManualAdContent         | 初回獲得手動広告コンテンツ（utm_content） |
| firstUserManualCampaignId        | 初回獲得手動キャンペーンID（utm_id） |
| firstUserManualCampaignName      | 初回獲得手動キャンペーン名（utm_campaign） |
| firstUserManualCreativeFormat    | 初回獲得手動クリエイティブ形式 |
| firstUserManualMarketingTactic   | 初回獲得手動マーケティング戦術 |
| firstUserManualMedium            | 初回獲得手動メディア（utm_medium） |
| firstUserManualSource            | 初回獲得手動参照元（utm_source） |
| firstUserManualSourceMedium      | 初回獲得手動参照元/メディア |
| firstUserManualSourcePlatform    | 初回獲得手動参照元プラットフォーム（utm_source_platform） |
| firstUserManualTerm              | 初回獲得手動キーワード（utm_term） |
| firstUserMedium                  | 初回獲得メディア |
| firstUserPrimaryChannelGroup     | 初回獲得メインチャネルグループ |
| firstUserSa360AdGroupId          | 初回獲得SA360広告グループID |
| firstUserSa360AdGroupName        | 初回獲得SA360広告グループ名 |
| firstUserSa360CampaignId         | 初回獲得SA360キャンペーンID |
| firstUserSa360CampaignName       | 初回獲得SA360キャンペーン名 |
| firstUserSa360CreativeFormat     | 初回獲得SA360クリエイティブ形式 |
| firstUserSa360EngineAccountId    | 初回獲得SA360エンジンアカウントID |
| firstUserSa360EngineAccountName  | 初回獲得SA360エンジンアカウント名 |
| firstUserSa360EngineAccountType    | 初回獲得SA360エンジンアカウント種類 |
| firstUserSa360KeywordText        | 初回獲得SA360キーワードテキスト |
| firstUserSa360ManagerAccountId   | 初回獲得SA360マネージャーアカウントID |
| firstUserSa360ManagerAccountName | 初回獲得SA360マネージャーアカウント名 |
| firstUserSa360Medium             | 初回獲得SA360メディア |
| firstUserSa360Query              | 初回獲得SA360検索クエリ |
| firstUserSa360Source             | 初回獲得SA360参照元 |
| firstUserSa360SourceMedium       | 初回獲得SA360参照元/メディア |
| firstUserSource                  | 初回獲得参照元 |
| firstUserSourceMedium            | 初回獲得参照元/メディア |
| firstUserSourcePlatform          | 初回獲得参照元プラットフォーム |
| fullPageUrl                      | 完全なページURL（ホスト名＋パス＋クエリ） |
| googleAdsAccountName             | Google広告アカウント名 |
| googleAdsAdGroupId               | Google広告広告グループID |
| googleAdsAdGroupName             | Google広告広告グループ名 |
| googleAdsAdNetworkType           | Google広告ネットワークタイプ |
| googleAdsCampaignId              | Google広告キャンペーンID |
| googleAdsCampaignName            | Google広告キャンペーン名 |
| googleAdsCampaignType            | Google広告キャンペーンタイプ |
| googleAdsCreativeId              | Google広告クリエイティブID |
| googleAdsCustomerId              | Google広告顧客ID |
| googleAdsKeyword                 | Google広告キーワード |
| googleAdsQuery                   | Google広告検索クエリ |
| groupId                          | ゲーム内プレイヤーグループID（group_idパラメータ） |
| hostName                         | ホスト名（サブドメイン＋ドメイン名） |
| hour                             | 記録時の時間（0～23） |
| isKeyEvent                       | キーイベントの場合は "true" |
| isoWeek                          | ISO週番号（例: 01～53） |
| isoYear                          | ISO年（例: 2022） |
| isoYearIsoWeek                   | ISO年と週番号の組合せ |
| itemAffiliation                  | アイテムアフィリエーション |
| itemBrand                        | アイテムブランド名 |
| itemCategory                     | アイテムカテゴリ（第1階層） |
| itemCategory2                    | アイテムカテゴリ2 |
| itemCategory3                    | アイテムカテゴリ3 |
| itemCategory4                    | アイテムカテゴリ4 |
| itemCategory5                    | アイテムカテゴリ5 |
| itemId                           | アイテムID |
| itemListId                       | アイテムリストID |
| itemListName                     | アイテムリスト名 |
| itemListPosition                 | リスト内のアイテム位置 |
| itemLocationID                   | アイテム地域ID（実店舗等） |
| itemName                         | アイテム名 |
| itemPromotionCreativeName        | プロモーションクリエイティブ名 |
| itemPromotionCreativeSlot        | プロモーション用クリエイティブスロット名 |
| itemPromotionId                  | アイテムプロモーションID |
| itemPromotionName                | アイテムプロモーション名 |
| itemVariant                      | アイテムのバリエーション（サイズ・色など） |
| landingPage                      | ランディングページパス |
| landingPagePlusQueryString       | ランディングページ＋クエリ文字列 |
| language                         | ブラウザ/デバイスの言語 |
| languageCode                     | 言語コード（例: en-us） |
| level                            | ゲーム内レベル |
| linkClasses                      | アウトバウンドリンクのHTMLクラス |
| linkDomain                       | リンク先ドメイン |
| linkId                           | リンクのHTML ID |
| linkText                         | ダウンロード用リンクテキスト |
| linkUrl                          | リンク先URL（外部リンク・ダウンロード） |
| manualAdContent                  | 手動広告コンテンツ（utm_content） |
| manualCampaignId                 | 手動キャンペーンID（utm_id） |
| manualCampaignName               | 手動キャンペーン名（utm_campaign） |
| manualCreativeFormat             | 手動クリエイティブ形式 |
| manualMarketingTactic            | 手動マーケティング戦術 |
| manualMedium                     | 手動メディア（utm_medium） |
| manualSource                     | 手動参照元（utm_source） |
| manualSourceMedium               | 手動参照元/メディア |
| manualSourcePlatform             | 手動参照元プラットフォーム（utm_source_platform） |
| manualTerm                       | 手動キーワード（utm_term） |
| medium                           | イベント貢献メディア |
| method                           | イベントトリガーメソッド |
| minute                           | 記録分（00～59） |
| mobileDeviceBranding             | デバイスブランド名 |
| mobileDeviceMarketingName        | ブランド付きデバイス名 |
| mobileDeviceModel                | モバイル機種名 |
| month                            | 記録月（01～12） |
| newVsReturning                   | 新規 or リピーター（new/returning） |
| nthDay                           | 経過日数（期間開始から） |
| nthHour                          | 経過時間（期間開始から） |
| nthMinute                        | 経過分数（期間開始から） |
| nthMonth                         | 経過月数（期間開始から） |
| nthWeek                          | 経過週数（期間開始から） |
| nthYear                          | 経過年数（期間開始から） |
| operatingSystem                  | オペレーティングシステム（例: Windows, Android） |
| operatingSystemVersion           | OSバージョン |
| operatingSystemWithVersion       | OSとバージョンの組合せ |
| orderCoupon                      | 注文クーポンコード |
| outbound                         | 外部リンクの場合 "true" |
| pageLocation                     | ページ完全URL（プロトコル含む） |
| pagePath                         | ページパス（ホスト名とクエリの間） |
| pagePathPlusQueryString          | ページパス＋クエリ文字列 |
| pageReferrer                     | 参照元URL（直前のページ） |
| pageTitle                        | ページタイトル |
| percentScrolled                  | スクロール率（例: 90） |
| platform                         | 実行プラットフォーム（ウェブ/ iOS/ Android） |
| platformDeviceCategory           | プラットフォーム/デバイスカテゴリ |
| primaryChannelGroup              | メインチャネルグループ |
| region                           | ユーザーアクション発生地域（IP由来） |
| sa360AdGroupId                   | SA360広告グループID |
| sa360AdGroupName                 | SA360広告グループ名 |
| sa360CampaignId                  | SA360キャンペーンID |
| sa360CampaignName                | SA360キャンペーン名 |
| sa360CreativeFormat              | SA360クリエイティブ形式 |
| sa360EngineAccountId             | SA360エンジンアカウントID |
| sa360EngineAccountName           | SA360エンジンアカウント名 |
| sa360EngineAccountType           | SA360エンジンアカウント種類 |
| sa360KeywordText                 | SA360キーワードテキスト |
| sa360ManagerAccountId            | SA360マネージャーアカウントID |
| sa360ManagerAccountName          | SA360マネージャーアカウント名 |
| sa360Medium                      | SA360メディア |
| sa360Query                       | SA360検索クエリ |
| sa360Source                      | SA360参照元 |
| sa360SourceMedium                | SA360参照元/メディア |
| screenResolution                 | 画面解像度 |
| searchTerm                       | 検索語句 |
| sessionCampaignId                | セッションキャンペーンID |
| sessionCampaignName              | セッションキャンペーン名 |
| sessionCm360AccountId            | セッションCM360アカウントID |
| sessionCm360AccountName          | セッションCM360アカウント名 |
| sessionCm360AdvertiserId         | セッションCM360広告主ID |
| sessionCm360AdvertiserName       | セッションCM360広告主名 |
| sessionCm360CampaignId           | セッションCM360キャンペーンID |
| sessionCm360CampaignName         | セッションCM360キャンペーン名 |
| sessionCm360CreativeFormat       | セッションCM360クリエイティブ形式 |
| sessionCm360CreativeId           | セッションCM360クリエイティブID |
| sessionCm360CreativeName         | セッションCM360クリエイティブ名 |
| sessionCm360CreativeType         | セッションCM360クリエイティブタイプ |
| sessionCm360CreativeTypeId       | セッションCM360クリエイティブタイプID |
| sessionCm360CreativeVersion      | セッションCM360クリエイティブバージョン |
| sessionCm360Medium               | セッションCM360メディア |
| sessionCm360PlacementCostStructure | セッションCM360プレースメント課金形態 |
| sessionCm360PlacementId          | セッションCM360プレースメントID |
| sessionCm360PlacementName        | セッションCM360プレースメント名 |
| sessionCm360RenderingId          | セッションCM360レンダリングID |
| sessionCm360SiteId               | セッションCM360サイトID |
| sessionCm360SiteName             | セッションCM360サイト名 |
| sessionCm360Source               | セッションCM360参照元 |
| sessionCm360SourceMedium         | セッションCM360参照元/メディア |
| sessionDefaultChannelGroup       | セッションデフォルトチャネルグループ |
| sessionDv360AdvertiserId         | セッションDV360広告主ID |
| sessionDv360AdvertiserName       | セッションDV360広告主名 |
| sessionDv360CampaignId           | セッションDV360キャンペーンID |
| sessionDv360CampaignName         | セッションDV360キャンペーン名 |
| sessionDv360CreativeFormat       | セッションDV360クリエイティブ形式 |
| sessionDv360CreativeId           | セッションDV360クリエイティブID |
| sessionDv360CreativeName         | セッションDV360クリエイティブ名 |
| sessionDv360ExchangeId           | セッションDV360エクスチェンジID |
| sessionDv360ExchangeName         | セッションDV360エクスチェンジ名 |
| sessionDv360InsertionOrderId     | セッションDV360広告掲載オーダーID |
| sessionDv360InsertionOrderName   | セッションDV360広告掲載オーダー名 |
| sessionDv360LineItemId           | セッションDV360広告申込情報ID |
| sessionDv360LineItemName         | セッションDV360広告申込情報名 |
| sessionDv360Medium               | セッションDV360メディア |
| sessionDv360PartnerId            | セッションDV360パートナーID |
| sessionDv360PartnerName          | セッションDV360パートナー名 |
| sessionDv360Source               | セッションDV360参照元 |
| sessionDv360SourceMedium         | セッションDV360参照元/メディア |
| sessionGoogleAdsAccountName      | セッションGoogle広告アカウント名 |
| sessionGoogleAdsAdGroupId        | セッションGoogle広告広告グループID |
| sessionGoogleAdsAdGroupName      | セッションGoogle広告広告グループ名 |
| sessionGoogleAdsAdNetworkType    | セッションGoogle広告ネットワークタイプ |
| sessionGoogleAdsCampaignId       | セッションGoogle広告キャンペーンID |
| sessionGoogleAdsCampaignName     | セッションGoogle広告キャンペーン名 |
| sessionGoogleAdsCampaignType     | セッションGoogle広告キャンペーンタイプ |
| sessionGoogleAdsCreativeId       | セッションGoogle広告クリエイティブID |
| sessionGoogleAdsCustomerId       | セッションGoogle広告顧客ID |
| sessionGoogleAdsKeyword          | セッションGoogle広告キーワード |
| sessionGoogleAdsQuery            | セッションGoogle広告検索クエリ |
| sessionManualAdContent           | セッション手動広告コンテンツ（utm_content） |
| sessionManualCampaignId          | セッション手動キャンペーンID（utm_id） |
| sessionManualCampaignName        | セッション手動キャンペーン名（utm_campaign） |
| sessionManualCreativeFormat      | セッション手動クリエイティブ形式 |
| sessionManualMarketingTactic     | セッション手動マーケティング戦術 |
| sessionManualMedium              | セッション手動メディア（utm_medium） |
| sessionManualSource              | セッション手動参照元（utm_source） |
| sessionManualSourceMedium        | セッション手動参照元/メディア |
| sessionManualSourcePlatform      | セッション手動参照元プラットフォーム（utm_source_platform） |
| sessionManualTerm                | セッション手動キーワード（utm_term） |
| sessionMedium                    | セッション開始時のメディア |
| sessionPrimaryChannelGroup       | セッションメインチャネルグループ |
| sessionSa360AdGroupId            | セッションSA360広告グループID |
| sessionSa360AdGroupName          | セッションSA360広告グループ名 |
| sessionSa360CampaignId           | セッションSA360キャンペーンID |
| sessionSa360CampaignName         | セッションSA360キャンペーン名 |
| sessionSa360CreativeFormat       | セッションSA360クリエイティブ形式 |
| sessionSa360EngineAccountId      | セッションSA360エンジンアカウントID |
| sessionSa360EngineAccountName    | セッションSA360エンジンアカウント名 |
| sessionSa360EngineAccountType    | セッションSA360エンジンアカウントタイプ |
| sessionSa360Keyword              | セッションSA360キーワード |
| sessionSa360ManagerAccountId     | セッションSA360マネージャーアカウントID |
| sessionSa360ManagerAccountName   | セッションSA360マネージャーアカウント名 |
| sessionSa360Medium               | セッションSA360メディア |
| sessionSa360Query                | セッションSA360検索クエリ |
| sessionSa360Source               | セッションSA360参照元 |
| sessionSa360SourceMedium         | セッションSA360参照元/メディア |
| sessionSource                    | セッション参照元 |
| sessionSourceMedium              | セッション参照元/メディア |
| sessionSourcePlatform            | セッション参照元プラットフォーム |
| shippingTier                     | 送料区分（配送方法） |
| signedInWithUserId               | User-IDでログイン済みなら "yes" |
| source                           | イベント貢献参照元 |
| sourceMedium                     | 参照元/メディア（sourceとmediumの組合せ） |
| sourcePlatform                   | 参照元プラットフォーム |
| streamId                         | データストリームID |
| streamName                       | データストリーム名 |
| testDataFilterId                 | テストデータフィルタID |
| testDataFilterName               | テストデータフィルタ名 |
| transactionId                    | eコマーストランザクションID |
| unifiedPagePathScreen            | ページパス/スクリーンクラス（イベント時） |
| unifiedPageScreen                | ページパス＋クエリ/スクリーンクラス |
| unifiedScreenClass               | ページタイトル＋スクリーンクラス |
| unifiedScreenName                | ページタイトル＋スクリーン名 |
| userAgeBracket                   | ユーザー年齢層 |
| userGender                       | ユーザー性別 |
| videoProvider                    | 動画プロバイダ（例: youtube） |
| videoTitle                       | 動画タイトル |
| videoUrl                         | 動画URL |
| virtualCurrencyName              | 仮想通貨名（ゲーム内通貨） |
| visible                          | 表示状態（trueなら表示） |
| week                             | イベント記録週（01～53） |
| year                             | イベント記録年（4桁） |
| yearMonth                        | 年と月の組合せ（例: 202212） |
| yearWeek                         | 年と週の組合せ（例: 202253） |`
